services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ExtensionBuilder\ExtensionBuilderTypo3\:
    resource: '../Classes/*'

  ExtensionBuilder\ExtensionBuilderTypo3\Command\ExtensionBuilderTypo3:
    tags:
      - name: console.command
        command: 'extensionbuilder:typo3'
        description: 'Extension Builder - Build TYPO3 Extension'
        schedulable: false

  dashboard.widget.extension_builder.typo3.overview:
    class: ExtensionBuilder\ExtensionBuilderTypo3\Widgets\Typo3OverviewWidget
    arguments:
      $options:
        template: 'Typo3OverviewWidget'
    tags:
      - name: dashboard.widget
        identifier: 'extensionbuilder.typo3.overview'
        groupNames: 'extensionbuilder'
        title: 'LLL:EXT:extensionbuilder_typo3/Resources/Private/Language/locallang.widgets.xlf:title'
        description: 'LLL:EXT:extensionbuilder_typo3/Resources/Private/Language/locallang.widgets.xlf:description'
        iconIdentifier: 'eb-logo-png'
        height: 'medium'
        width: 'medium'
