services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ExtensionBuilder\ExtensionbuilderTypo3\:
    resource: '../Classes/*'

  ExtensionBuilder\ExtensionbuilderTypo3\Service\ExtensionBuilderService:
    shared: true